clone_folder: c:\gopath\src\github.com\DonnchaC\oniongateway

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - go get -t github.com/DonnchaC/oniongateway/...
  - go test github.com/DonnchaC/oniongateway/...
  - >
      %GOPATH%/bin/overalls -project=github.com/DonnchaC/oniongateway
  - >
      %GOPATH%/bin/goveralls
      -coverprofile=overalls.coverprofile
      -service=appveyor-ci
      -repotoken=%COVERALLS_TOKEN%
